exomedepth:
  bedfile:
    checksum: b3306819a11936d94abe2a26f26dc0d9
    path: marple/TwistCancer_Probes_merged_ok_combined_Uppsala_InheritedCancer_v5_SR_TE-96855960_hg38_200bpwindows.bed
    type: file
    url: file:/projects/wp3/nobackup/TwistCancer/TCv5-1/Bedfiles/TwistCancer_Probes_merged_ok_combined_Uppsala_InheritedCancer_v5_SR_TE-96855960_hg38_200bpwindows.bed
  exonsfile:
    checksum: f3ed2cb6706065422ef72d307d82452f
    path: marple/exons_GRCh38_ensembl109.txt
    type: file
    url: file:/beegfs-storage/data/ref_data/wp3/marple/exons_GRCh38_ensembl109.txt
  genesfile:
    checksum: a72c9c1608e07cd8d3a1bfd1f65106ee
    path: marple/genes_GRCh38_ensembl109.txt
    type: file
    url: file:/beegfs-storage/data/ref_data/wp3/marple/genes_GRCh38_ensembl109.txt
  references:
    miseq:
      checksum: 4a18d1e3e159973ddfb454c56b014e3d
      path: marple/Exomedepth_refCount_230706.Rdata
      type: file
      url: file:/beegfs-storage/data/ref_data/wp3/marple/Exomedepth_refCount_230706.Rdata
    novaseqX:
      checksum: b52ef521a2668398ce9ae2fd464237f5
      path: marple/Exomedepth_refCount_NovaSeq_250120.Rdata
      type: file
      url: file:/beegfs-storage/data/ref_data/wp3/marple/Exomedepth_refCount_NovaSeq_250120.Rdata
