# Marvin site override following the standard config/site layout.

PIPELINE_HOME: /projects/bin/wp3_tc/marple_rd_tc/{{PIPELINE_VERSION}}/marple_rd_tc
REFERENCE_DATA_DIR: /projects/cgu/library/references/GRCh38
CONTAINER_DIR: /projects/wp4/nobackup/singularity_cache
HYDRA_MODULES_DIR: /projects/bin/wp3_tc/marple_rd_tc/{{PIPELINE_VERSION}}/hydra-genetics
RESOURCES_FILE: config/resources.yaml
PACKAGED_REF_DIR: /projects/wp3/nobackup/TwistCancer/Bedfiles

resources: "{{RESOURCES_FILE}}"
hydra_local_path: "{{HYDRA_MODULES_DIR}}"
output: "{{PIPELINE_HOME}}/config/output_files.yaml"

reference:
  annovar: "/opt/ohpc/pub/annotators/annovar/2025Feb18"
  fasta: "/data/ref_genomes/GRCh38/reference_grasnatter/homo_sapiens.fasta"
  fai: "/data/ref_genomes/GRCh38/reference_grasnatter/homo_sapiens.fasta.fai"
  sites: "/data/ref_genomes/GRCh38/reference_grasnatter/homo_sapiens.known_indels.vcf.gz"
  design_bed: "{{PACKAGED_REF_DIR}}/Twist_Cancer_230608_hg38_TE-98982205-wPGRS.merged.bed"
  design_intervals: "{{PACKAGED_REF_DIR}}/Twist_Cancer_230608_hg38_TE-98982205-wPGRS.merged.intervals"
  exon_bed: "{{PACKAGED_REF_DIR}}/Twist_Cancer_230602_hg38_coding_exons.bed"
  exon_intervals: "{{PACKAGED_REF_DIR}}/Twist_Cancer_230602_hg38_coding_exons.intervals"
  pgrs_bed: "{{PACKAGED_REF_DIR}}/Twist_Cancer_230707_hg38_pgrs_snps.bed"

bwa_mem:
  amb: "/data/ref_genomes/GRCh38/reference_grasnatter/homo_sapiens.fasta.amb"
  ann: "/data/ref_genomes/GRCh38/reference_grasnatter/homo_sapiens.fasta.ann"
  bwt: "/data/ref_genomes/GRCh38/reference_grasnatter/homo_sapiens.fasta.bwt"
  pac: "/data/ref_genomes/GRCh38/reference_grasnatter/homo_sapiens.fasta.pac"
  sa: "/data/ref_genomes/GRCh38/reference_grasnatter/homo_sapiens.fasta.sa"

exomedepth_call:
  bedfile: "{{PACKAGED_REF_DIR}}/Twist_Cancer_230706_hg38_TE-98982205-wPGRS.merged_200bpwindows.bed"
  exonsfile: "{{PACKAGED_REF_DIR}}/exons_GRCh38_ensembl109.txt"
  genesfile: "{{PACKAGED_REF_DIR}}/genes_GRCh38_ensembl109.txt"

export_qc_xlsx_report:
  wanted_transcripts: "{{PACKAGED_REF_DIR}}/wanted_transcripts.txt"

vep:
  vep_cache: "/data/ref_genomes/VEP"
