# Miarka site override following the standard config/site layout.

PIPELINE_HOME: /proj/ngi2024001/nobackup/bin/wp3_tc/{{PIPELINE_VERSION}}/marple_rd_tc
REFERENCE_DATA_DIR: /proj/ngi2024001/nobackup/cgu/library/references/GRCh38
CONTAINER_DIR: /proj/ngi2024001/nobackup/bin/wp3_tc/apptainer_cache
HYDRA_MODULES_DIR: /proj/ngi2024001/nobackup/bin/wp3_tc/{{PIPELINE_VERSION}}/hydra-genetics
RESOURCES_FILE: config/resources.miarka.yaml
PACKAGED_REF_DIR: /proj/ngi2024001/nobackup/bin/wp3_tc/design_and_ref_files/marple

resources: "{{RESOURCES_FILE}}"
hydra_local_path: "{{HYDRA_MODULES_DIR}}"
default_container: "{{CONTAINER_DIR}}/hydragenetics__common_3.1.1.sif"
output: "{{PIPELINE_HOME}}/config/output_files.yaml"

reference:
  annovar: "{{PACKAGED_REF_DIR}}/annovar/"
  fasta: "{{PACKAGED_REF_DIR}}/reference_grasnatter/homo_sapiens.fasta"
  fai: "{{PACKAGED_REF_DIR}}/reference_grasnatter/homo_sapiens.fasta.fai"
  sites: "{{PACKAGED_REF_DIR}}/reference_grasnatter/homo_sapiens.known_indels.vcf.gz"
  design_bed: "{{PACKAGED_REF_DIR}}/Twist_Cancer_230608_hg38_TE-98982205-wPGRS.merged.bed"
  design_intervals: "{{PACKAGED_REF_DIR}}/Twist_Cancer_230608_hg38_TE-98982205-wPGRS.merged.intervals"
  exon_bed: "{{PACKAGED_REF_DIR}}/Twist_Cancer_230602_hg38_coding_exons.bed"
  exon_intervals: "{{PACKAGED_REF_DIR}}/Twist_Cancer_230602_hg38_coding_exons.intervals"
  pgrs_bed: "{{PACKAGED_REF_DIR}}/Twist_Cancer_230707_hg38_pgrs_snps.bed"

bwa_mem:
  amb: "{{PACKAGED_REF_DIR}}/reference_grasnatter/homo_sapiens.fasta.amb"
  ann: "{{PACKAGED_REF_DIR}}/reference_grasnatter/homo_sapiens.fasta.ann"
  bwt: "{{PACKAGED_REF_DIR}}/reference_grasnatter/homo_sapiens.fasta.bwt"
  pac: "{{PACKAGED_REF_DIR}}/reference_grasnatter/homo_sapiens.fasta.pac"
  sa: "{{PACKAGED_REF_DIR}}/reference_grasnatter/homo_sapiens.fasta.sa"

exomedepth_call:
  bedfile: "{{PACKAGED_REF_DIR}}/Twist_Cancer_230706_hg38_TE-98982205-wPGRS.merged_200bpwindows.bed"
  exonsfile: "{{PACKAGED_REF_DIR}}/exons_GRCh38_ensembl109.txt"
  genesfile: "{{PACKAGED_REF_DIR}}/genes_GRCh38_ensembl109.txt"

export_qc_xlsx_report:
  wanted_transcripts: "{{PACKAGED_REF_DIR}}/wanted_transcripts.txt"

melt:
  bed: "{{PACKAGED_REF_DIR}}/melt/Hg38.genes.bed"
  mei: "{{PACKAGED_REF_DIR}}/melt/mei_list.txt"

mosaicforecast_genotype_prediction:
  model_trainedSNP: "{{PACKAGED_REF_DIR}}/150xRFmodel_addRMSK_Refine.rds"
  model_trainedINS: "{{PACKAGED_REF_DIR}}/insertions_250x.RF.rds"
  model_trainedDEL: "{{PACKAGED_REF_DIR}}/deletions_250x.RF.rds"

vep:
  vep_cache: "{{PACKAGED_REF_DIR}}/VEP/"
